/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobSlugRouteImport } from './routes/jobs/$jobSlug'
import { Route as EmployerPostJobRouteImport } from './routes/employer/post-job'
import { Route as EmployerInterviewsRouteImport } from './routes/employer/interviews'
import { Route as EmployerDashboardRouteImport } from './routes/employer/dashboard'
import { Route as EmployerCompanyProfileRouteImport } from './routes/employer/company-profile'
import { Route as EmployerCandidatesRouteImport } from './routes/employer/candidates'
import { Route as CandidateSavedRouteImport } from './routes/candidate/saved'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateDiscoverRouteImport } from './routes/candidate/discover'
import { Route as CandidateDashboardRouteImport } from './routes/candidate/dashboard'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate/applications'
import { Route as CandidateAlertsRouteImport } from './routes/candidate/alerts'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as EmployerApplicantsJobIdRouteImport } from './routes/employer/applicants.$jobId'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobSlugRoute = JobsJobSlugRouteImport.update({
  id: '/jobs/$jobSlug',
  path: '/jobs/$jobSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPostJobRoute = EmployerPostJobRouteImport.update({
  id: '/employer/post-job',
  path: '/employer/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerInterviewsRoute = EmployerInterviewsRouteImport.update({
  id: '/employer/interviews',
  path: '/employer/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCompanyProfileRoute = EmployerCompanyProfileRouteImport.update({
  id: '/employer/company-profile',
  path: '/employer/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/employer/candidates',
  path: '/employer/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSavedRoute = CandidateSavedRouteImport.update({
  id: '/candidate/saved',
  path: '/candidate/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDiscoverRoute = CandidateDiscoverRouteImport.update({
  id: '/candidate/discover',
  path: '/candidate/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAlertsRoute = CandidateAlertsRouteImport.update({
  id: '/candidate/alerts',
  path: '/candidate/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicantsJobIdRoute = EmployerApplicantsJobIdRouteImport.update({
  id: '/employer/applicants/$jobId',
  path: '/employer/applicants/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/candidate/alerts': typeof CandidateAlertsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/discover': typeof CandidateDiscoverRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/saved': typeof CandidateSavedRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/company-profile': typeof EmployerCompanyProfileRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/interviews': typeof EmployerInterviewsRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/jobs/$jobSlug': typeof JobsJobSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/employer/applicants/$jobId': typeof EmployerApplicantsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/candidate/alerts': typeof CandidateAlertsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/discover': typeof CandidateDiscoverRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/saved': typeof CandidateSavedRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/company-profile': typeof EmployerCompanyProfileRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/interviews': typeof EmployerInterviewsRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/jobs/$jobSlug': typeof JobsJobSlugRoute
  '/jobs': typeof JobsIndexRoute
  '/employer/applicants/$jobId': typeof EmployerApplicantsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/candidate/alerts': typeof CandidateAlertsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/discover': typeof CandidateDiscoverRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/saved': typeof CandidateSavedRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/company-profile': typeof EmployerCompanyProfileRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/interviews': typeof EmployerInterviewsRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/jobs/$jobSlug': typeof JobsJobSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/employer/applicants/$jobId': typeof EmployerApplicantsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/discover'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employer/candidates'
    | '/employer/company-profile'
    | '/employer/dashboard'
    | '/employer/interviews'
    | '/employer/post-job'
    | '/jobs/$jobSlug'
    | '/jobs/'
    | '/employer/applicants/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/discover'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employer/candidates'
    | '/employer/company-profile'
    | '/employer/dashboard'
    | '/employer/interviews'
    | '/employer/post-job'
    | '/jobs/$jobSlug'
    | '/jobs'
    | '/employer/applicants/$jobId'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/discover'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employer/candidates'
    | '/employer/company-profile'
    | '/employer/dashboard'
    | '/employer/interviews'
    | '/employer/post-job'
    | '/jobs/$jobSlug'
    | '/jobs/'
    | '/employer/applicants/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CandidateAlertsRoute: typeof CandidateAlertsRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateDiscoverRoute: typeof CandidateDiscoverRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateSavedRoute: typeof CandidateSavedRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerCompanyProfileRoute: typeof EmployerCompanyProfileRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerInterviewsRoute: typeof EmployerInterviewsRoute
  EmployerPostJobRoute: typeof EmployerPostJobRoute
  JobsJobSlugRoute: typeof JobsJobSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
  EmployerApplicantsJobIdRoute: typeof EmployerApplicantsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobSlug': {
      id: '/jobs/$jobSlug'
      path: '/jobs/$jobSlug'
      fullPath: '/jobs/$jobSlug'
      preLoaderRoute: typeof JobsJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/post-job': {
      id: '/employer/post-job'
      path: '/employer/post-job'
      fullPath: '/employer/post-job'
      preLoaderRoute: typeof EmployerPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/interviews': {
      id: '/employer/interviews'
      path: '/employer/interviews'
      fullPath: '/employer/interviews'
      preLoaderRoute: typeof EmployerInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/company-profile': {
      id: '/employer/company-profile'
      path: '/employer/company-profile'
      fullPath: '/employer/company-profile'
      preLoaderRoute: typeof EmployerCompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/employer/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/saved': {
      id: '/candidate/saved'
      path: '/candidate/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof CandidateSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/discover': {
      id: '/candidate/discover'
      path: '/candidate/discover'
      fullPath: '/candidate/discover'
      preLoaderRoute: typeof CandidateDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/alerts': {
      id: '/candidate/alerts'
      path: '/candidate/alerts'
      fullPath: '/candidate/alerts'
      preLoaderRoute: typeof CandidateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applicants/$jobId': {
      id: '/employer/applicants/$jobId'
      path: '/employer/applicants/$jobId'
      fullPath: '/employer/applicants/$jobId'
      preLoaderRoute: typeof EmployerApplicantsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CandidateAlertsRoute: CandidateAlertsRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateDiscoverRoute: CandidateDiscoverRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateSavedRoute: CandidateSavedRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerCompanyProfileRoute: EmployerCompanyProfileRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerInterviewsRoute: EmployerInterviewsRoute,
  EmployerPostJobRoute: EmployerPostJobRoute,
  JobsJobSlugRoute: JobsJobSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
  EmployerApplicantsJobIdRoute: EmployerApplicantsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
